# Kubernetes deployment description for Identifiers.org Resource Recommender API Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1
kind: Deployment
metadata:
    name: resource-recommender
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: resource-recommender
    replicas: 1
    template:
        metadata:
            labels:
                environment: production
                tier: api
                app: resource-recommender
        spec:
            tolerations:
            - key: "iorg-node-reliability-ephemeral-noschedule"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
            affinity:
              nodeAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 5
                    preference:
                      matchExpressions:
                        - key: iorg-node-reliability
                          operator: In
                          values:
                            - stable
              podAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 70
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                          - key: environment
                            operator: In
                            values:
                            - production
                          - key: tier
                            operator: In
                            values:
                            - api
                          - key: app
                            operator: In
                            values:
                            - link-checker
                      topologyKey: "kubernetes.io/hostname"
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 50
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                        - key: environment
                          operator: In
                          values:
                          - production
                        - key: tier
                          operator: In
                          values:
                          - api
                        - key: app
                          operator: In
                          values:
                          - resource-recommender
                      topologyKey: "kubernetes.io/hostname"
            containers:
                - name: cloud-ws-resource-recommender
                  image: identifiersorg/cloud-ws-resource-recommender:1.1.1
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: 440Mi
                          cpu: 200m
                      limits:
                          memory: 440Mi
                  env:
                  - name: WS_RESOURCE_RECOMMENDER_JVM_MEMORY_MAX
                    value: "420m"
                  - name: WS_RESOURCE_RECOMMENDER_CONFIG_BACKEND_SERVICE_LINK_CHECKER_HOST
                    value: link-checker
                  ports:
                  - containerPort: 8083
