# Kubernetes deployment description for Identifiers.org Link Checker Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: link-checker
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: link-checker
    replicas: 1
    template:
        metadata:
            labels:
                environment: production
                tier: api
                app: link-checker
        spec:
            containers:
                - name: cloud-ws-link-checker
                  image: identifiersorg/cloud-ws-link-checker:1.0.4
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: 640Mi
                  env:
                  - name: WS_LINK_CHECKER_JVM_MEMORY_MAX
                    value: "512m"
                  ports:
                  - containerPort: 8084
