# Kubernetes deployment description for Identifiers.org Resolver Web Service
#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: resolver
spec:
    selector:
        matchLabels:
            environment: production
            tier: api
            app: resolver
    replicas: 2
    template:
        metadata:
            labels:
                environment: production
                tier: api
                app: resolver
        spec:
            containers:
                - name: cloud-ws-resolver
                  image: identifiersorg/cloud-ws-resolver:1.0.4
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: 640Mi
                  env:
                  - name: WS_RESOLVER_CONFIG_REDIS_HOST
                    value: "redis"
                  - name: WS_RESOLVER_CONFIG_REDIS_PORT
                    value: "6379"
                  - name: WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_HOST
                    value: "resource-recommender"
                  - name: WS_RESOLVER_CONFIG_RESOURCE_RECOMMENDER_PORT
                    value: "8083"
                  - name: WS_RESOLVER_JVM_MEMORY_MAX
                    value: "512m"
                  ports:
                  - containerPort: 8080
