# Kubernetes deployment description for Identifiers.org Satellite Web Frontend
#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: web-frontend
spec:
    selector:
        matchLabels:
            environment: production
            tier: frontend
            app: web-frontend
    replicas: 2
    template:
        metadata:
            labels:
                environment: production
                tier: frontend
                app: web-frontend
        spec:
            containers:
                - name: cloud-web-frontend
                  image: identifiersorg/cloud-web-frontend:0.0.8
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: 512Mi
                  env:
                  - name: WEB_CONFIG_SERVICE_RESOLVER_HOST
                    value: "resolver.api.aws.identifiers.org"
                  - name: WEB_CONFIG_SERVICE_RESOLVER_PORT
                    value: "80"
                  - name: WEB_CONFIG_SERVICE_REGISTRY_HOST
                    value: "registry.api.aws.identifiers.org"
                  - name: WEB_CONFIG_SERVICE_REGISTRY_PORT
                    value: "80"
                  ports:
                  - containerPort: 9090
