---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.keycloak.component }}
  labels:
    tier: {{ .Values.keycloak.tier }}
    component: {{ .Values.keycloak.component }}
    {{- (include "common_labels" .) | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: {{ .Values.keycloak.tier }}
      component: {{ .Values.keycloak.component }}
      {{- (include "common_labels" .) | indent 6 }}
  template:
    metadata:
      labels:
        tier: {{ .Values.keycloak.tier }}
        component: {{ .Values.keycloak.component }}
        {{- (include "common_labels" .) | indent 8 }}
    spec:
      affinity:
        {{- (include "node_affinity_requirements" .) | indent 8 }}
      containers:
        - name: {{ .Values.keycloak.component }}
          image: {{ .Values.keycloak.image }}
          resources:
            requests:
              memory: {{ .Values.keycloak.requests.memory }}
              cpu: {{ .Values.keycloak.requests.cpu }}
          command: [ "/opt/keycloak/bin/kc.sh" ]
          args: [ "start", "--optimized" ]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hq-keycloak-credentials-admin
                  key: username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hq-keycloak-credentials-admin
                  key: password
            - name: KC_DB
              value: {{ .Values.keycloak.database.vendor | quote }}
            - name: KC_DB_URL
              value: {{ .Values.keycloak.database.url | quote }}
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hq-keycloak-db-credentials
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hq-keycloak-db-credentials
                  key: password
            - name: JGROUPS_DISCOVERY_PROTOCOL
              value: "dns.DNS_PING"
            - name: JGROUPS_DISCOVERY_PROPERTIES
              value: "dns_query=keycloak.default.svc.cluster.local"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            {{- toYaml .Values.keycloak.env | nindent 12 }}
          ports:
            - containerPort: {{ .Values.keycloak.port }}
            - containerPort: 9000
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /management/health/ready
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /management/health/live
              port: 9000
            initialDelaySeconds: 19
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
  name: {{ .Values.keycloak.component }}
  labels:
    tier: {{ .Values.keycloak.tier }}
    component: {{ .Values.keycloak.component }}
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.keycloak.port }}
    - name: management
      protocol: TCP
      port: 9000
  selector:
    tier: {{ .Values.keycloak.tier }}
    component: {{ .Values.keycloak.component }}
    {{- (include "common_labels" .) | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
  name: nodeport-{{ .Values.keycloak.component }}
  labels:
    tier: {{ .Values.keycloak.tier }}
    component: {{ .Values.keycloak.component }}
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.keycloak.port }}
    - name: management
      protocol: TCP
      port: 9000
  selector:
    tier: {{ .Values.keycloak.tier }}
    component: {{ .Values.keycloak.component }}
    {{- (include "common_labels" .) | indent 4 }}
  type: NodePort
---