# This file contains properties to be used when AAA is enabled
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI:http://localkeycloak:8080/auth/realms/scratchpad/}
        registration:
          keycloak:
            client-id: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID:hq-registry}
            client-secret: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET:29d9150c-14b4-46b5-a7fb-e634101cb020}
      resourceserver:
        jwt:
          issuer-uri: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI:http://localkeycloak:8080/auth/realms/scratchpad}