# This file contains properties to be used when AAA is enabled, this configuration contains both resource server and client information
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI:http://localkeycloak:8080/auth/realms/scratchpad}
        registration:
          keycloak:
            grantType: client_credentials
            accessTokenUri: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_ACCESS_TOKEN_URI:http://localkeycloak:8080/auth/realms/scratchpad/protocol/openid-connect/token}
            client-id: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID:hq-registry}
            client-secret: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET:4ec8bb52-941c-4bdb-83fd-dd9d521d3964}
      resourceserver:
        jwt:
          issuer-uri: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI:http://localkeycloak:8080/auth/realms/scratchpad}