# This file contains properties to be used when AAA is enabled, this configuration contains both resource server and client information
management:
  endpoint:
    health:
      show-details: when_authorized

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI:http://localkeycloak:8080/auth/realms/idorg}
        registration:
          keycloak:
            client-id: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID:hq-registry}
            client-secret: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET:secrety-secret}
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_basic
      resourceserver:
        jwt:
          issuer-uri: ${HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI:http://localkeycloak:8080/auth/realms/idorg}