# Kubernetes deployment description for Identifiers.org Redis service within Identifiers.org platform
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
spec:
    selector:
        matchLabels:
            environment: production
            tier: backend
            app: redis
            deployment: satellite
    replicas: 1
    template:
        metadata:
            labels:
                environment: production
                tier: backend
                app: redis
                deployment: satellite
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                              - key: iorg-node-reliability
                                operator: In
                                values:
                                - stable
            containers:
                - name: redis
                  image: redis:4.0.8-alpine
                  imagePullPolicy: Always
                  resources:
                      requests:
                          memory: 1280Mi
                  ports:
                  - containerPort: 6379
