# Development environment definition
# Author: Manuel Bernal Llinares
version: "3.5"
services:
    postgresql:
        image: postgres
        environment:
            - POSTGRES_DB=devdatabase
            - POSTGRES_USER=devusername
            - POSTGRES_PASSWORD=devpassword
        ports:
            - "5430:5432"
        volumes:
            - "registry:/var/lib/postgresql/data"
    redis:
        image: redis:4.0.8-alpine
        ports:
            - "6379:6379"
    hqregistry:
        image: identifiersorg/cloud-hq-ws-registry
        environment:
            - HQ_WS_REGISTRY_CONFIG_JDBC_URL=jdbc:postgresql://postgresql:5432/devdatabase
            - HQ_WS_REGISTRY_CONFIG_RDBMS_USERNAME=devusername
            - HQ_WS_REGISTRY_CONFIG_RDBMS_PASSWORD=devpassword
            - HQ_WS_REGISTRY_CONFIG_BACKEND_SERVICE_MIRID_CONTROLLER_HOST=hqmiridcontroller
            - HQ_WS_REGISTRY_CONFIG_BACKEND_SERVICE_MIRID_CONTROLLER_PORT=8181
            - HQ_WS_REGISTRY_CONFIG_APPLICATION_ACTIVE_PROFILE=development,authenabled
            - HQ_WS_REGISTRY_CONFIG_CORS_ORIGIN=*
            - HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI=http://localkeycloak:8080/auth/realms/idorg
            - HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_ACCESS_TOKEN_URI=http://localkeycloak:8080/auth/realms/idorg/protocol/openid-connect/token
            - HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID=hq-registry
            - HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET=clientsecret
            - HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://localkeycloak:8080/auth/realms/idorg
            - HQ_WS_REGISTRY_CONFIG_EMAIL_HOST=fakesmtp
            - HQ_WS_REGISTRY_CONFIG_EMAIL_PORT=25
        ports:
            - "8180:8180"
        depends_on:
            - postgresql
            - hqmiridcontroller
            - localkeycloak
            - fakesmtp
        restart: on-failure
    hqmiridcontroller:
        image: identifiersorg/cloud-hq-ws-mirid-controller
        environment:
            - HQ_WS_MIRID_CONTROLLER_CONFIG_JDBC_URL=jdbc:postgresql://postgresql:5432/devdatabase
            - HQ_WS_MIRID_CONTROLLER_CONFIG_RDBMS_USERNAME=devusername
            - HQ_WS_MIRID_CONTROLLER_CONFIG_RDBMS_PASSWORD:devpassword
            - HQ_WS_MIRID_CONTROLLER_CONFIG_REDIS_HOST=redis
            - HQ_WS_MIRID_CONTROLLER_CONFIG_REDIS_PORT=6379
            - HQ_WS_MIRID_CONTROLLER_CONFIG_APPLICATION_ACTIVE_PROFILE=development,authenabled
            - HQ_WS_MIRID_CONTROLLER_CONFIG_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI=http://localkeycloak:8080/auth/realms/idorg/
            - HQ_WS_MIRID_CONTROLLER_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID=hq-mirid-controller
            - HQ_WS_MIRID_CONTROLLER_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET=clientsecret
            - HQ_WS_MIRID_CONTROLLER_CONFIG_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://localkeycloak:8080/auth/realms/idorg
        ports:
            - "8181:8181"
        depends_on:
            - redis
            - postgresql
            - localkeycloak
        restart: on-failure
    localkeycloak:
        image: jboss/keycloak:6.0.1
        volumes:
            - ./data/keycloak:/srv/keycloak
        environment:
            - KEYCLOAK_USER=devadmin
            - KEYCLOAK_PASSWORD=devpassword
            - DB_VENDOR=postgres
            - DB_ADDR=postgresql
            - DB_DATABASE=devdatabase
            - DB_USER=devusername
            - DB_PASSWORD=devpassword
            - KEYCLOAK_IMPORT=/srv/keycloak/realm-idorg-dev.json
        ports:
            - "8080:8080"
        depends_on:
            - postgresql
        healthcheck:
            test: curl -f http://localhost:8080/auth/
            start_period: 30s
    fakesmtp:
        image: digiplant/fake-smtp
        ports:
            - "1025:25"
        volumes:
            - ./tmp/fakesmtp:/var/mail
networks:
    default:
        name: hqwebnet
volumes:
    registry:
        name: idorg_registry
        driver: local