services:
    mirid-postgresql:
        image: postgres
        environment:
            - POSTGRES_DB=devdatabase
            - POSTGRES_USER=devusername
            - POSTGRES_PASSWORD=devpassword
        ports:
            - "5431:5432"
        volumes:
            - "../../db/mirid-controller:/docker-entrypoint-initdb.d"
    registry-postgresql:
        image: postgres
        environment:
            - POSTGRES_DB=devdatabase
            - POSTGRES_USER=devusername
            - POSTGRES_PASSWORD=devpassword
        ports:
            - "5430:5432"
        volumes:
            - "../../db/registry:/docker-entrypoint-initdb.d"
    redis:
        image: redis:7.4-alpine
        ports:
            - "6379:6379"
    hqregistry:
        image: identifiersorg/cloud-hq-ws-registry
        environment:
            - HQ_WS_REGISTRY_CONFIG_JDBC_URL=jdbc:postgresql://registry-postgresql:5432/devdatabase
            - HQ_WS_REGISTRY_CONFIG_RDBMS_USERNAME=devusername
            - HQ_WS_REGISTRY_CONFIG_RDBMS_PASSWORD=devpassword
            - HQ_WS_REGISTRY_CONFIG_BACKEND_SERVICE_MIRID_CONTROLLER_HOST=hqmiridcontroller
            - HQ_WS_REGISTRY_CONFIG_BACKEND_SERVICE_MIRID_CONTROLLER_PORT=8181
            - HQ_WS_REGISTRY_CONFIG_APPLICATION_ACTIVE_PROFILE=authdisabled
            - HQ_WS_REGISTRY_CONFIG_EMAIL_HOST=fakesmtp
            - HQ_WS_REGISTRY_CONFIG_EMAIL_PORT=25
        ports:
            - "8180:8180"
        depends_on:
            - registry-postgresql
            - hqmiridcontroller
            - fakesmtp
    hqmiridcontroller:
        image: identifiersorg/cloud-hq-ws-mirid-controller
        environment:
            - HQ_WS_MIRID_CONTROLLER_CONFIG_JDBC_URL=jdbc:postgresql://mirid-postgresql:5432/devdatabase
            - HQ_WS_MIRID_CONTROLLER_CONFIG_RDBMS_USERNAME=devusername
            - HQ_WS_MIRID_CONTROLLER_CONFIG_RDBMS_PASSWORD:devpassword
            - HQ_WS_MIRID_CONTROLLER_CONFIG_REDIS_HOST=redis
            - HQ_WS_MIRID_CONTROLLER_CONFIG_APPLICATION_ACTIVE_PROFILE=authdisabled
        ports:
            - "8181:8181"
        depends_on:
            - redis
            - mirid-postgresql
    fakesmtp:
        image: digiplant/fake-smtp
        ports:
            - "1025:25"
networks:
    default:
        name: hqwebnet