# Kubernetes declaration of Identifiers.org Web Frontend Service
#
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: v1
kind: Service
metadata:
    name: web-frontend
    labels:
        environment: production
        tier: frontend
        app: web-frontend
spec:
    ports:
    - port: 9090
    selector:
        environment: production
        tier: frontend
        app: web-frontend
