apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.registry.component }}
spec:
  selector:
    matchLabels:
      tier: {{ .Values.registry.tier }}
      component: {{ .Values.registry.component }}
      {{- (include "common_labels" .) | indent 6 }}
  replicas: {{ .Values.registry.replicas }}
  template:
    metadata:
      labels:
        tier: {{ .Values.registry.tier }}
        component: {{ .Values.registry.component }}
        {{- (include "common_labels" .) | indent 8 }}
    spec:
      affinity:
        {{- (include "node_affinity_requirements" .) | indent 8 }}
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    {{- (include "common_label_match_expressions" .) | indent 20 }}
                    - key: tier
                      operator: In
                      values:
                        - {{ .Values.mirid_controller.tier }}
                    - key: component
                      operator: In
                      values:
                        - {{ .Values.mirid_controller.component }}
                topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    {{- (include "common_label_match_expressions" .) | indent 20 }}
                    - key: tier
                      operator: In
                      values:
                        - {{ .Values.registry.tier }}
                    - key: component
                      operator: In
                      values:
                        - {{ .Values.registry.component }}
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: cloud-hq-ws-registry
          image: {{ .Values.registry.image }}
          resources:
            requests:
              memory: {{ .Values.registry.requests.memory }}
              cpu: {{ .Values.registry.requests.cpu }}
          env:
            - name: HQ_WS_REGISTRY_CONFIG_JDBC_URL
              {{- with .Values.registry.database }}
              value: {{ (printf "jdbc:%s://%s:%s/%s" .driver .host (toString .port) .dbname) | quote }}
              {{- end }}
            - name: HQ_WS_REGISTRY_CONFIG_RDBMS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hq-registry-database-credentials
                  key: username
            - name: HQ_WS_REGISTRY_CONFIG_RDBMS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hq-registry-database-credentials
                  key: password
            - name: HQ_WS_REGISTRY_CONFIG_BACKEND_SERVICE_MIRID_CONTROLLER_HOST
              value: "mirid-controller"
            - name: HQ_WS_REGISTRY_CONFIG_BACKEND_SERVICE_MIRID_CONTROLLER_PORT
              value: {{ .Values.mirid_controller.port | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_CORS_ORIGIN
              value: {{ .Values.registry.cors_origins | quote }}
            - name: HQ_WS_REGISTRY_JVM_MEMORY_MAX
              value: {{ .Values.registry.requests.memory | lower | trimSuffix "i" | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUERURI
              value: {{ .Values.keycloak.issuer_uri | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_ACCESS_TOKEN_URI
              value: {{ .Values.keycloak.access_token_uri | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: hq-registry-keycloak-credentials
                  key: clientid
            - name: HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: hq-registry-keycloak-credentials
                  key: clientsecret
            - name: HQ_WS_REGISTRY_CONFIG_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI
              value: {{ .Values.keycloak.issuer_uri |quote }}
            - name: HQ_WS_REGISTRY_CONFIG_APPLICATION_ACTIVE_PROFILE
              value: "authenabled"
            # E-mail Server configuration
            - name: HQ_WS_REGISTRY_CONFIG_EMAIL_HOST
              value: {{ .Values.mailer.host | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_EMAIL_PORT
              value: {{ .Values.mailer.port | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hq-registry-smtp-credentials
                  key: username
            - name: HQ_WS_REGISTRY_CONFIG_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hq-registry-smtp-credentials
                  key: password
            - name: HQ_WS_REGISTRY_CONFIG_EMAIL_TRANSPORT_PROTOCOL
              value: {{ .Values.mailer.protocol | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_SMTP_AUTH
              value: {{ .Values.mailer.smtp_auth | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_START_TLS
              value: {{ .Values.mailer.start_tls | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_EMAIL_BOOLEAN_DEBUG
              value: "false"
            # E-mail Notifiers configuration - Common
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_FROM
              value: {{ .Values.mailer.notifications.from }}
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_REPLY_TO
              value: {{ .Values.mailer.notifications.reply_to }}
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_EMAIL_CURATION
              value: {{ .Values.mailer.notifications.curators | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_EMAIL_SUPPORT
              value: {{ .Values.mailer.notifications.main | quote }}
            # E-mail Notifiers configuration - CURATOR - Prefix Registration Request START
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_CURATOR_PREFIXREG_START_TO
              value: {{ .Values.mailer.notifications.main | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_CURATOR_PREFIXREG_START_CC
              value: {{ .Values.mailer.notifications.curators | quote }}
            # E-mail Notifiers configuration - REQUESTER - Prefix Registration Request START
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_REQUESTER_PREFIXREG_START_CC
              value: ""
            # E-mail Notifiers configuration - REQUESTER - Prefix Registration Request ACCEPTANCE
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_REQUESTER_PREFIXREG_ACCEPTANCE_CC
              value: {{ .Values.mailer.notifications.curators | quote }}
            # E-mail Notifiers configuration - REQUESTER - Prefix Registration Request REJECTION
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_REQUESTER_PREFIXREG_REJECTION_CC
              value: {{ .Values.mailer.notifications.curators | quote }}
            # E-mail Notifiers configuration - CURATOR - Resource Registration Request START
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_CURATOR_RESOURCEREG_START_TO
              value: {{ .Values.mailer.notifications.main | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_CURATOR_RESOURCEREG_START_CC
              value: {{ .Values.mailer.notifications.curators | quote }}
            # E-mail Notifiers configuration - REQUESTER - Resource Registration Request START
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_REQUESTER_RESOURCEREG_START_CC
              value: ""
            # E-mail Notifiers configuration - REQUESTER - Resource Registration Request ACCEPTANCE
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_REQUESTER_RESOURCEREG_ACCEPTANCE_CC
              value: {{ .Values.mailer.notifications.curators | quote }}
            # E-mail Notifiers configuration - REQUESTER - Resource Registration Request REJECTION
            - name: HQ_WS_REGISTRY_CONFIG_NOTIFIERS_REQUESTER_RESOURCEREG_REJECTION_CC
              value: {{ .Values.mailer.notifications.curators | quote }}
            - name: MATOMO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: matomo-credentials
                  key: auth_token
            - name: MATOMO_ENABLED
              value: {{ .Values.matomo.enabled | quote }}
            - name: MATOMO_BASE_URL
              value: {{ .Values.matomo.base_url | default "" | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_BACKEND_REQUIRED_ROLE
              value: {{ .Values.actuator_auth.role | quote }}
            - name: HQ_WS_REGISTRY_CONFIG_URL_PATTERN_SIMILARITY_THRESHOLD
              value: {{ .Values.registry.url_pattern_similarity_threshold | quote }}
            {{- range $key, $val := .Values.registry.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end}}
          ports:
            - containerPort: {{ .Values.registry.port }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/readiness
              port: {{ .Values.registry.port }}
            initialDelaySeconds: 45
            periodSeconds: 30
            timeoutSeconds: 25
            failureThreshold: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health/liveness
              port: {{ .Values.registry.port }}
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 25
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
  name: {{ .Values.registry.component }}
  labels:
    tier: {{ .Values.registry.tier }}
    component: {{ .Values.registry.component }}
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: {{ .Values.registry.port }}
  selector:
    tier: {{ .Values.registry.tier }}
    component: {{ .Values.registry.component }}
    {{- (include "common_labels" .) | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
  name: nodeport-{{ .Values.registry.component }}
  labels:
    tier: {{ .Values.registry.tier }}
    component: {{ .Values.registry.component }}
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: {{ .Values.registry.port }}
  selector:
    tier: {{ .Values.registry.tier }}
    component: {{ .Values.registry.component }}
    {{- (include "common_labels" .) | indent 4 }}
  type: NodePort
