---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.component }}
  labels:
    tier: {{ .Values.frontend.tier }}
    component: {{ .Values.frontend.component }}
    {{- (include "common_labels" .) | indent 4 }}
spec:
  selector:
    matchLabels:
      tier: {{ .Values.frontend.tier }}
      component: {{ .Values.frontend.component }}
      {{- (include "common_labels" .) | indent 6 }}
  replicas: {{ .Values.frontend.replicas }}
  template:
    metadata:
      labels:
        tier: {{ .Values.frontend.tier }}
        component: {{ .Values.frontend.component }}
        {{- (include "common_labels" .) | indent 8 }}
    spec:
      affinity:
        {{- (include "node_affinity_requirements" .) | indent 8 }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    {{- (include "common_label_match_expressions" .) | indent 20 }}
                    - key: tier
                      operator: In
                      values:
                        - {{ .Values.frontend.tier }}
                    - key: component
                      operator: In
                      values:
                        - {{ .Values.frontend.component }}
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: hq-registry-web
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: {{ .Values.frontend.requests.memory }}
              cpu: {{ .Values.frontend.requests.cpu }}
          env:
            - name: ENVCONFIG_HQ_WEB_REGISTRY_CONFIG_API_REGISTRY_URL
              value: {{ .Values.registry.api_uri | quote }}
            - name: ENVCONFIG_HQ_WEB_REGISTRY_CONFIG_AUTH_URL
              value: {{ .Values.keycloak.base_uri | quote }}
            - name: ENVCONFIG_HQ_WEB_REGISTRY_CONFIG_AUTH_REDIRECT_URI
              value: {{ .Values.registry.base_uri | quote }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 90
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":false}'
  name: nodeport-{{ .Values.frontend.component }}
  labels:
    tier: {{ .Values.frontend.tier }}
    component: {{ .Values.frontend.component }}
    {{- (include "common_labels" .) | indent 4 }}
spec:
  ports:
    - port: {{ .Values.frontend.port }}
  selector:
    tier: {{ .Values.frontend.tier }}
    component: {{ .Values.frontend.component }}
    {{- (include "common_labels" .) | indent 4 }}
  type: NodePort
---