# Development environment HQ Registry API Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
services:
    postgresql:
        image: postgres
        environment:
            - POSTGRES_DB=devdatabase
            - POSTGRES_USER=devusername
            - POSTGRES_PASSWORD=devpassword
        ports:
            - "5430:5432"
        volumes:
            - "../../db/registry:/docker-entrypoint-initdb.d"
    miridpostgresql:
        image: postgres
        environment:
            - POSTGRES_DB=devdatabase
            - POSTGRES_USER=devusername
            - POSTGRES_PASSWORD=devpassword
        ports:
            - "5431:5432"
        volumes:
            - "../../db/mirid-controller:/docker-entrypoint-initdb.d"
    redis:
        image: redis:4.0.8-alpine
        ports:
            - "6379:6379"
    link-checker:
        image: identifiersorg/cloud-ws-link-checker
        environment:
            - WS_LINK_CHECKER_CONFIG_REDIS_HOST=redis
            - WS_LINK_CHECKER_CONFIG_REDIS_PORT=6379
            - WS_LINK_CHECKER_CONFIG_BACKEND_SERVICE_RESOLVER_HOST=localhost
            - WS_LINK_CHECKER_CONFIG_DAEMON_PERIODIC_LINK_CHECK_REQUESTER_ENABLED=false
            - WS_LINK_CHECKER_CONFIG_BACKEND_SERVICE_JWT_ISSUERURI=https://auth.identifiers.org/auth/realms/idorg
            - SPRING_PROFILES_ACTIVE=authdisabled
        ports:
            - "8084:8084"
        depends_on:
            - redis
    miridcontroller:
        image: identifiersorg/cloud-hq-ws-mirid-controller
        environment:
            - HQ_WS_MIRID_CONTROLLER_CONFIG_JDBC_URL=jdbc:postgresql://miridpostgresql:5432/devdatabase
            - HQ_WS_MIRID_CONTROLLER_CONFIG_RDBMS_USERNAME=devusername
            - HQ_WS_MIRID_CONTROLLER_CONFIG_RDBMS_PASSWORD=devpassword
            - HQ_WS_MIRID_CONTROLLER_CONFIG_REDIS_HOST=redis
            - HQ_WS_MIRID_CONTROLLER_CONFIG_APPLICATION_ACTIVE_PROFILE=development,authdisabled
        ports:
            - "8181:8181"
        depends_on:
            - redis
            - miridpostgresql
    fakesmtp:
        image: digiplant/fake-smtp
        ports:
            - "3025:25"
        volumes:
            - ./tmp/fakesmtp:/var/mail
networks:
    default:
        name: idorg-dev-hq-registry
volumes:
    registry:
        name: idorg_registry
        external: true