# Kubernetes declaration of Identifiers.org Compact ID Resolution API Service
# Author: Manuel Bernal Llinares <mbdebian@gmail.com>
apiVersion: v1
kind: Service
metadata:
    name: nodeport-sparql
    labels:
        environment: production
        tier: api
        app: sparql
        deployment: satellite
spec:
    ports:
    - port: 8080
    selector:
        environment: production
        tier: api
        app: sparql
        deployment: satellite
    type: NodePort
