name: Build Jekyll site
on:
  push:
    branches: ["master"]
    paths: ["docs/**"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        uses: actions/jekyll-build-pages@v1
        working-directory: '/docs/'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        working-directory: '/docs/'
  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        working-directory: '/docs/'
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}