
include ./libapi/Makefile
include ./link-checker/Makefile
include ./metadata/Makefile
include ./mirid-controller/Makefile
include ./registry/Makefile
include ./resolver/Makefile
include ./resource-recommender/Makefile
include ./satellite-webspa/Makefile
include ./sparql/Makefile
include ./validator-registry/Makefile